"""Schema type-name constants used throughout the template system.

These are string constants that identify types and properties in the
JSON schema files (workflow-v1.0.json, action-v1.0.json).
"""

ALLOWED_VALUES = "allowed-values"
ANY = "any"
BOOLEAN = "boolean"
BOOLEAN_DEFINITION = "boolean-definition"
BOOLEAN_DEFINITION_PROPERTIES = "boolean-definition-properties"
CLOSE_EXPRESSION = "}}"
CONSTANT = "constant"
CONTEXT = "context"
DEFINITION = "definition"
DEFINITIONS = "definitions"
DESCRIPTION = "description"
IGNORE_CASE = "ignore-case"
INSERT_DIRECTIVE = "insert"
IS_EXPRESSION = "is-expression"
ITEM_TYPE = "item-type"
LOOSE_KEY_TYPE = "loose-key-type"
LOOSE_VALUE_TYPE = "loose-value-type"
MAX_CONSTANT = "MAX"
MAPPING = "mapping"
MAPPING_DEFINITION = "mapping-definition"
MAPPING_DEFINITION_PROPERTIES = "mapping-definition-properties"
MAPPING_PROPERTY_VALUE = "mapping-property-value"
NON_EMPTY_STRING = "non-empty-string"
NULL = "null"
NULL_DEFINITION = "null-definition"
NULL_DEFINITION_PROPERTIES = "null-definition-properties"
NUMBER = "number"
NUMBER_DEFINITION = "number-definition"
NUMBER_DEFINITION_PROPERTIES = "number-definition-properties"
ONE_OF = "one-of"
ONE_OF_DEFINITION = "one-of-definition"
OPEN_EXPRESSION = "${{"
PROPERTY_VALUE = "property-value"
PROPERTIES = "properties"
REQUIRED = "required"
REQUIRE_NON_EMPTY = "require-non-empty"
SCALAR = "scalar"
SEQUENCE = "sequence"
SEQUENCE_DEFINITION = "sequence-definition"
SEQUENCE_DEFINITION_PROPERTIES = "sequence-definition-properties"
TYPE = "type"
SEQUENCE_OF_NON_EMPTY_STRING = "sequence-of-non-empty-string"
STRING = "string"
STRING_DEFINITION = "string-definition"
STRING_DEFINITION_PROPERTIES = "string-definition-properties"
STRUCTURE = "structure"
TEMPLATE_SCHEMA = "template-schema"
VERSION = "version"
